version: "3.4"

services:
  web:
    image: codeforacause/pink-flag-app:#{TAG_NUMBER}#
    container_name: pink-flag-app
    ports:
      - "8000:80"
    environment:
      DB_NAME: "db"
      DB_USER: "#{DB_USERNAME}#"
      DB_PASSWORD: "#{DB_PASSWORD}#"
      DB_HOST: "db"

  db:
    image: postgres:13.5-alpine
    container_name: pink-flag-db
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: "db"
      POSTGRESS_USER: "#{DB_USERNAME}#"
      POSTGRES_PASSWORD: "#{DB_PASSWORD}#"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
