version: "3.4"

services:
  web:
    image: codeforacause/pink-flag-app:#{TAG_NUMBER}#
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    command: python app/manage.py runserver 0.0.0.0:80
    environment:
      DB_NAME: "db"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"

  db:
    image: postgres:13.5-alpine
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: "db"
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
