version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:80
    environment:
      DB_NAME: "db"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
    restart: always
    depends_on: 
      - db

  db:
    image: postgres:13.5-alpine
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: "db"
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
    restart: always
