# Generated by Django 4.1.2 on 2023-05-24 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='enable_notifications',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='consumer',
            name='cycle_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumer',
            name='google_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='menstruation_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumer',
            name='menstruation_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
