# Generated by Django 4.1.2 on 2023-05-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pink_flag_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='consumer',
        ),
    ]
