# Generated by Django 4.1.2 on 2023-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_donationpage_copy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
