name: CI
on:
  push:
    branches:
      - main
jobs:
  Main_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Building docker image
        run: docker build ./backend/ -t codeforacause/pink-flag-app:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR
        run: docker push codeforacause/pink-flag-app:${{ github.run_number }}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/backend/docker-compose.pink-flag.yaml"]'
        env:
          TAG_NUMBER: "${{ github.run_number }}"
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # - name: copy file via ssh password
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     source: "./backend/docker-compose.pink-flag.yaml"
      #     target: "./Projects/pink-flag-app/"
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./backedn/docker-compose.pink-flag.yaml
          remote: ./Projects/pink-flag-app/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f ./Projects/pink-flag-app/backend/docker-compose.pink-flag.yaml up -d
