name: CI
on:
  push:
    branches:
      - main
jobs:
  Develop_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Building docker image
        run: docker build ./backend/ -t codeforacause/pink-flag-app:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR
        run: docker push codeforacause/pink-flag-app:${{ github.run_number }}
      - name: executing remote ssh commands using password
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: deploy.sh
